encord-team/encord-active

- src/encord_active/app/cli/main.py
- src/encord_active/app/cli/utils.py
- src/encord_active/lib/metrics/fetch_prebuilt_metrics.py
1. Adds `encord-active hello` command.
2. Bypasses the `streamlit` email quesion on first run.
> feat(cli): Hello command.

- src/encord_active/lib/model_predictions/writer.py
Polygon points are converted to absolute values.
> Fix: convert imported polygon points to absolute values

- src/encord_active/lib/charts/precision_recall.py
Sorting of object classes' mAP is added to the metric page so that users can now get the best and worst performing object classes easily.
> feat(predictions): add sorting to the object class mAP

- src/encord_active/lib/metrics/example.py
Fix broken method name in the docs.
> fix(example-metric): update name of `perform_test`

- examples/maskrcnn-example/readme.md
- examples/maskrcnn-example/train.py
- examples/maskrcnn-example/utils/model_libs.py
- examples/maskrcnn-example/workflows/improve_dataset_by_fixing_labels.md
Saves checkpoint at the last epoch in addition to the best epoch.
> Feat (maskrcnn-example): Save last epoch

- src/encord_active/cli/imports.py
- src/encord_active/cli/main.py
- src/encord_active/cli/utils/prints.py
- src/encord_active/lib/coco/importer.py
- src/encord_active/lib/encord/local_sdk.py
- src/encord_active/lib/project/local.py
The functionality for importing a local dataset based off glob.
Documentation will come in a separate PR shortly.
> feat(import): init project from data directory

- README.md
- docs/docs/cli/import-encord-project.md
- docs/docs/getting-started.md
- src/encord_active/cli/utils/encord.py
- src/encord_active/lib/encord/utils.py
Now that we had the new framework for querying in place, I had to improve the import encord project experience.
> feat: fuzzy project search for encord projects

- src/encord_active/cli/main.py
- src/encord_active/lib/project/sandbox_projects.py
The following projects are added to the sandbox projects:
- TACO-Official
- TACO-Unofficial
- rareplanes
> Feat (sandbox): New sandbox projects

- docs/builders/build_metrics_pages.py
- src/encord_active/app/actions_page/export_filter.py
- src/encord_active/app/views/model_quality.py
- src/encord_active/cli/main.py
- src/encord_active/lib/constants.py
Commands for opening resources.
```
encord-active docs
encord-active join-slack
```
> feat(cli): add links to resources

- src/encord_active/app/common/components/metric_summary.py
- src/encord_active/app/common/state.py
- src/encord_active/app/data_quality/sub_pages/summary.py
- src/encord_active/lib/dataset/outliers.py
- src/encord_active/lib/dataset/summary_utils.py
Data quality summary and label quality summary pages have different information to report; therefore, their layout will be different in the future. They need to be separated.
> Refactor: summary dashboards

- src/encord_active/lib/dataset/outliers.py
- src/encord_active/lib/dataset/summary_utils.py
> fix: df schema type

- src/encord_active/lib/dataset/summary_utils.py
- src/encord_active/lib/embeddings/cnn.py
fix: check that label row has classification answer
> fix: duplicate classifications in same label row crashes embeddings

- docs/builders/build_metrics_pages.py
- docs/docs/faq.mdx
- docs/docs/metrics/geometric.md
- docs/docs/metrics/heuristic.md
- docs/docs/metrics/semantic.md
- src/encord_active/lib/metrics/heuristic/missing_objects_and_wrong_tracks.py
1. Remove unnecessary content from FAQ
2. Rerun build script for metrics to get in latest updates
> docs: fixes from docbash v2

- src/encord_active/app/actions_page/export_balance.py
- src/encord_active/app/actions_page/export_filter.py
- src/encord_active/app/actions_page/versioning.py
- src/encord_active/app/common/state.py
- src/encord_active/app/common/state_hooks.py
- src/encord_active/app/data_quality/sub_pages/explorer.py
- src/encord_active/app/streamlit_entrypoint.py
This change would allow creating states with a default of `None`, e.g. 
```python
state = UseState[Optional[int]]()
state.value == None # -> True, and the type of is correct
```
> feat(use-state): make hooks truly generic

- src/encord_active/app/actions_page/export_filter.py
- src/encord_active/app/common/utils.py
> feat(export): show filter stats

- docs/docs/metrics/data-quality-metrics.md
- src/encord_active/lib/metrics/semantic/image_difficulty.py
- src/encord_active/lib/metrics/semantic/image_easiness.py
This metric ranks images according to their proximity to its class's cluster center. For more info, please check the documentation.
> Feat (metrics): image easiness

- src/encord_active/lib/metrics/acquisition_functions.py
- src/encord_active/lib/metrics/geometric/annotation_duplicates.py
- src/encord_active/lib/metrics/geometric/hu_static.py
- src/encord_active/lib/metrics/geometric/hu_temporal.py
- src/encord_active/lib/metrics/geometric/image_border_closeness.py
- src/encord_active/lib/metrics/geometric/object_size.py
- src/encord_active/lib/metrics/geometric/occlusion_detection_video.py
- src/encord_active/lib/metrics/heuristic/high_iou_changing_classes.py
- src/encord_active/lib/metrics/heuristic/img_features.py
- src/encord_active/lib/metrics/heuristic/missing_objects_and_wrong_tracks.py
- src/encord_active/lib/metrics/heuristic/object_counting.py
- src/encord_active/lib/metrics/heuristic/random.py
url to metric docs are updated.
> fix (metrics): update doc urls

- docs/docs/cli.md
- src/encord_active/cli/main.py
- src/encord_active/lib/common/utils.py
- src/encord_active/lib/project/project.py
Includes:
1. Refresh project capabilities
2. CLI refresh command
3. Medium refactor of data and labels download capabilities to make an easier transition to the new-to-come filesystem
Missing:
1. Docs in the CLI (on it on the morning of March 30, 2023)
Problem: The mappings in the label rows structures are troublesome as they weren't designed having in mind that the data may change over time. They don't have a way to construct paths that don't exist yet so I had to manually force the name of the files in the filesystem in the project code (at least this is not a big issue as it was already done that way).
> feat: smart refresh of project data

- src/encord_active/lib/project/project.py
Fixing a regression introduced by the `project refresh` feature.
> fix: download data when importing projects from encord

- src/encord_active/app/actions_page/export_filter.py
There may be a better way of doing this but this solves the immediate challenge of having a coco export script.
> Fix coco export.

- frontend_components/src/encord_active_components/frontend/src/components/explorer/Explorer.tsx
- frontend_components/src/encord_active_components/frontend/src/components/explorer/api.ts
- src/encord_active/server/main.py
- src/encord_active/server/utils.py
With this PR will support:
- Classifications
- bboxes
- polylines
- key points
Also, Description was included on hover.
> feat(explorer): support more annotation types and description

- src/encord_active/lib/project/project.py
Encord SDK is sending a bad format for the datetimes with comma valued datetimes like the following `2022-08-10 17:34:58.649359` and it affects the refresh capability as this error only occurs at label row metadata level, not the label row itself. Now, we trim the faulty numbers and leave it in the proper format while the Encord SDK push a fix and new version.
> fix: encord sdk bad datetime format

- examples/README.md
These will run successfully when the new version is out due to the latest SDK change.
> feat (examples): add new colab notebooks

- src/encord_active/app/actions_page/export_filter.py
Select all frames:
Select frames that have some labels:
Select frames without labels:
> feat: add "No class" option when filtering by object class

- src/encord_active/app/actions_page/export_filter.py
- src/encord_active/lib/encord/actions.py
- src/encord_active/lib/encord/project_sync.py
- src/encord_active/lib/project/project.py
- src/encord_active/lib/project/project_file_structure.py
Fixes subset execution for remote projects (tested against internal all-in-one project)
Verified upload still works with these changes.
Reduced from earlier version of the pr as some of the code changes were not needed on further investigation.
> fix: remote subset

- src/encord_active/cli/utils/encord.py
- src/encord_active/lib/db/helpers/tags.py
- src/encord_active/lib/labels/ontology.py
Tagging nested classifications at import.
Still doesn't work for project refreshes though.
> feat: tag nested classifications

- docs/.editorconfig
- docs/docs/getting-started.mdx
- docs/docs/import/index.mdx
- docs/docs/index.mdx
- docs/docs/installation.mdx
- docs/docs/known-issues.md
- docs/docs/metrics/_category_.json
The changes modify the following sections:
1. Overview
2. Getting Started
3. Installation
4. Import (Front Page) 
5. Known issues
Note: The notebooks that appear on these sections have been updated. They won't appear as part of this PR as they live in google colab.
> docs: minor improvements and fixes

- src/encord_active/lib/coco/encoder.py
- src/encord_active/lib/common/data_utils.py
- src/encord_active/lib/common/image_utils.py
- src/encord_active/lib/common/iterator.py
- src/encord_active/lib/db/data/migrations/202306141700_prefer_relative_paths.py
- src/encord_active/lib/encord/actions.py
- src/encord_active/lib/encord/local_sdk.py
- src/encord_active/lib/encord/project_sync.py
- src/encord_active/lib/project/project.py
- src/encord_active/lib/project/project_file_structure.py
- src/encord_active/server/utils.py
fixes issue caused by coco files occasionally generated un-normalised uri's.
also means that moving projects works more reliably.
> fix: prefer relative path uri in database

- src/encord_active/lib/encord/actions.py
> fix: KeyError for upload to encord

- src/encord_active/cli/imports.py
- src/encord_active/cli/main.py
- src/encord_active/cli/project.py
- src/encord_active/cli/utils/encord.py
- src/encord_active/lib/common/data_utils.py
- src/encord_active/lib/project/metadata.py
- src/encord_active/lib/project/project.py
- src/encord_active/lib/project/project_file_structure.py
For cases where re-downloading data on-demand is expensive
> feat: export --store-data-locally argument for encord project imports

- docs/docs/import/import-coco-project.md
- docs/docs/import/import-encord-project.md
- docs/docs/import/import-predictions.mdx
- docs/docs/import/quick-import-data.md
The changes include modifications to the following doc sections:
1. Quick import
2. Import model predictions
3. Import from Encord Annotate
4. Import from COCO project
> docs: import section revision

- docs/docs/getting-started.mdx
1. Currently only shared view only locally. I'll update to anyone can view once ready to land.
2. Encord docs will need to be updated on the site.
> fix: Use new nginx variant of google collab in docs.

- src/encord_active/lib/common/iterator.py
Total frames are calculated based on this PR: https://github.com/encord-team/cord-backend/pull/1469
> Feat (iterator): download all video frames

- src/encord_active/cli/imports.py
- src/encord_active/db/scripts/delete_project.py
- src/encord_active/db/scripts/migrate_disk_to_db.py
- src/encord_active/lib/model_predictions/types.py
- src/encord_active/server/routers/project.py
- src/encord_active/server/routers/project2_prediction.py
Misc fixes from me and Frederick r.e prediction handling
> fix: prediction calculation bugs

- frontend_components/encord_active_components/frontend/src/components/Types.ts
- frontend_components/encord_active_components/frontend/src/components/charts/ChartDistributionBar.tsx
- frontend_components/encord_active_components/frontend/src/components/charts/ChartOutlierSummaryBar.tsx
- frontend_components/encord_active_components/frontend/src/components/charts/ChartPredictionMetricPerformanceChart.tsx
- frontend_components/encord_active_components/frontend/src/components/tabs/predictions/PredictionSummaryTab.tsx
- frontend_components/encord_active_components/frontend/src/components/tabs/predictions/PredictionsMetricPerformanceTab.tsx
- frontend_components/encord_active_components/frontend/src/components/tabs/predictions/PredictionsTab.tsx
- pyproject.toml
- src/encord_active/db/enums.py
- src/encord_active/db/metrics.py
- src/encord_active/server/routers/project2_prediction.py
fix: prediction page update when project changed & import rot bounding box
fix: prediction calculation & agreement on what to display
> fix: Many thing re prediction & formatting

- frontend_components/encord_active_components/frontend/src/components/explorer/Explorer.tsx
reset page when filters change
> fix: reset page after changing filters

- frontend_components/encord_active_components/frontend/src/components/explorer/Explorer.tsx
> fix: explorer ui make buttons look similar

- frontend_components/encord_active_components/frontend/src/components/explorer/Explorer.tsx
- src/encord_active/server/utils.py
There was a but that sometimes the cards would not show the class names in the explorer.
> fix: show classifications in explorer

- frontend_components/encord_active_components/frontend/src/components/IntegratedAPI.ts
- frontend_components/encord_active_components/frontend/src/components/explorer/Explorer.tsx
- frontend_components/encord_active_components/frontend/src/components/explorer/Tagging.tsx
- frontend_components/encord_active_components/frontend/src/components/explorer/api.ts
- frontend_components/encord_active_components/frontend/src/components/explorer/id.ts
- frontend_components/encord_active_components/frontend/src/components/util/MetricFilter.tsx
- src/encord_active/lib/common/filtering.py
- src/encord_active/lib/db/helpers/tags.py
- src/encord_active/server/routers/project.py
- src/encord_active/server/utils.py
Backend seems to more or less work. There are some issues around FE tagging where tags disappear. See latest commit message.
> fix: use tags from db

- frontend_components/encord_active_components/frontend/src/components/explorer/Tagging.tsx
- src/encord_active/server/routers/project.py
Also, in explorer tags should be set and not list
> fix: tags match frames and not only data unit

- frontend_components/encord_active_components/frontend/src/components/explorer/Tagging.tsx
- src/encord_active/server/dependencies.py
- src/encord_active/server/routers/project.py
Tagging was very slow, when tagging big amounts of data. This PR taks tagging 30K items on my mac from ~30sec to ~3 sec. Not I think that major bottleneck is communitation.
> perf: tagging

- src/encord_active/cli/main.py
- src/encord_active/cli/utils/server.py
- src/encord_active/server/start_server.py
Set app port either with `PORT` env variable or with `--port` CLI argument
> feat: flexible app port

- pyproject.toml
after a few local build & install iterations, got something to work.
Not sure which of the set of changes are needed. But it works.
> fix: encourage pip to include frontend dist folder
