encord-team/encord-active

src/encord_active/lib/model_predictions/writer.py
Fixing `points_to_mask` function to both handle normalized and absolute values.
=> fix: importing polygon points

src/encord_active/cli/utils/encord.py
Instead of printing
```shell
cd /absolute/path/to/the/downloaded/project
```
print
```shell
cd relative/path/to/project
```
when project is a subdirectory of current working directory.
=> fix(import): fix relative path and print for project import

src/encord_active/lib/coco/encoder.py
An image/object that has tags is not suited for `pd.isnull(..)` as it compares each tag against null instead of the container of the tags (a list), so tags need to be handled separately.
Also, now the encoding will output tag names instead of the tag class representation. We still need to address the issue of tag names containing emojis added by EA to clean a little more the output json.
=> Fix(encoder): tag handling

src/encord_active/app/common/state.py, src/encord_active/cli/imports.py, src/encord_active/lib/common/iterator.py, src/encord_active/lib/dataset/balance.py, src/encord_active/lib/db/connection.py, src/encord_active/lib/db/predictions.py, src/encord_active/lib/encord/actions.py, src/encord_active/lib/model_predictions/importers.py, src/encord_active/lib/model_predictions/iterator.py, src/encord_active/lib/model_predictions/writer.py, src/encord_active/lib/project/__init__.py, src/encord_active/lib/project/project.py, src/encord_active/lib/project/project_file_structure.py
**Context**: Latest addition of `ProjectFileStructure` class allows to declare paths via file system references in `ProjectFileStructure` instead of explicitly declaring how to construct such paths each time they are needed with the subsequent error/bug chances and loss of portability from one project file structure to another. At the time of writing this PR the explicit file structure version is predominant across the codebase and we aim to encapsulate usage of every file system related path through `ProjectFileStructure` class.
This PR starts enforcing `ProjectFileStructure` as the main and only way to access file/dir paths of project's elements (e.g. image, label row json, metadata). The following changes were applied:
- `project_dir` attribute was removed from `Project` class to …
=> Refactor: enforce project file structure usage

src/encord_active/app/common/components/annotator_statistics.py, src/encord_active/app/common/components/label_statistics.py, src/encord_active/app/data_quality/sub_pages/explorer.py, src/encord_active/lib/metrics/utils.py
With this PR, no multiselect nor statistics related to `object_class`/`annotator` will be shown if `object_class` or `annotator` information are undefined in the data.
Also, `NaN` values are not shown as an option in the multiselects related to `object_class` and `annotator`.
These changes effectively remove `object_class` and `annotator` multiselects and statistics in the data quality explorer and as a side effect in some metrics, like `Frame Object Density`, in the label quality explorer where no `object_class` nor `annotator` are available.
=> chore: remove unnecessary statistics in explorer

src/encord_active/lib/metrics/geometric/hu_static.py, src/encord_active/lib/metrics/geometric/hu_temporal.py, src/encord_active/lib/metrics/geometric/object_size.py, src/encord_active/lib/metrics/geometric/occlusion_detection_video.py, src/encord_active/lib/metrics/heuristic/_annotation_time.py, src/encord_active/lib/metrics/heuristic/img_features.py, src/encord_active/lib/metrics/heuristic/missing_objects_and_wrong_tracks.py, src/encord_active/lib/metrics/metric.py, src/encord_active/lib/metrics/semantic/_class_uncertainty.py, src/encord_active/lib/metrics/semantic/_heatmap_uncertainty.py, src/encord_active/lib/metrics/utils.py
Recent refactoring actions decoupled the `app` from `lib`, in this PR we remove `score_normalization` boolean attribute from the metric class as this behaviour is expected to be managed by the `app`.
=> refactor: remove score normalisation from metric definition

src/encord_active/lib/coco/encoder.py
`flickr_url` attribute is expected in the COCO format. An empty string is added for that attribute.
=> fix (COCO export): add flick_url attribute

examples/maskrcnn-example/example_config.ini, examples/maskrcnn-example/generate_ea_predictions.py, examples/maskrcnn-example/train.py
mAP calculation takes too much time; therefore, it is optional for the training set now.
=> feat (maskrcnn-example): make training log optional

src/encord_active/lib/common/iterator.py, src/encord_active/lib/project/project.py
Image paths and data units are sorted in a different fashion so they can't be used in a per index fashion, but instead linked by their data unit hash.
=> fix(iterator): link correct image paths to data units on image groups

src/encord_active/app/common/components/annotator_statistics.py
Mean score for all annotations was calculated via the average of annotator's mean scores, instead of `total_score_sum`/`total_annotations`.
=> fix(app): update mean score value in annotator stats

src/encord_active/lib/common/image_utils.py, src/encord_active/lib/model_predictions/reader.py
Bounding box predictions doesn't work for two reasons:
1. The dataframe schemas that we defined for the predictions didn't allow empty RLEs. When a bounding box prediction is imported in the app, the rle will be NaN in the data frames because they don't have a mask. This is fixed.
2. The plotting of the predictions in the TP, FP, and FN pages were missing objects, as they expected an RLE. This is fixed.
We should introduce an object detection dataset to the sandbox datasets to be able to test these things regularly.
=> fix(predictions): properly draw bounding box predictions

examples/maskrcnn-example/utils/downscale_dataset.py, src/encord_active/lib/coco/importer.py, src/encord_active/lib/common/image_utils.py, src/encord_active/lib/common/utils.py, src/encord_active/lib/embeddings/cnn.py, src/encord_active/lib/metrics/heuristic/img_features.py, src/encord_active/lib/model_predictions/importers.py
Some corrupted images have not been captured by current checks so we broaden them in order to avoid app failure. Next iterations will add error log handling to detect these special cases and handle them accordingly.
=> fix: broader exception handling range when reading images

src/encord_active/cli/imports.py, src/encord_active/cli/utils/decorators.py
Before, running commands that require a project directory would fail like this:
Now we do 3 things:
1. If one of the target's parents is a project directory, we use that
2. If any of the immediate children of the target is a project directory, prompt the user to select which one to execute the command on
3. Otherwise, show help text
=> fix(cli): target option more informative help text

src/encord_active/cli/print.py, src/encord_active/lib/common/utils.py
Print ontology was broken for locally imported projects. Now the command looks for the locally available `ontology.json` file instead of querying the SDK.
=> fix(cli): printing ontology looks for json instead of using sdk

src/encord_active/cli/main.py
Now, users can add metric names to `metricize` command with the optional input `--add` (`-a`) in case they already know the name of the metrics they want to execute. This implementation allows the user to run the `metricize` command in a non-interactive fashion keeping it simple for the user to rerun the same metrics.
=> Feat(cli): add non-interactive use of metricize

src/encord_active/lib/metrics/heuristic/img_features.py
Now, the code tries to obtain image width and height from the data unit first instead of opening an image to read that metadata.
Also, some markdown beautification was done in place.
=> Feat: improve area and aspect ratio metrics efficiency

src/encord_active/lib/common/image_utils.py
We were not showing the masks for segmentation predictions.
=> fix(app): show masks for rle predictions

docs/docs/cli/download-sandbox-data.md
An image path directed to `rareplanes.png` instead of actual file `Rareplanes.png`. Fixed.
=> docs: correct image path to link to actual file

src/encord_active/app/common/components/metric_summary.py
Based on the discussions [here](https://github.com/encord-team/encord-active/pull/156)
=> fix: avoids renaming a dataframe view

src/encord_active/lib/metrics/metric.py, src/encord_active/lib/metrics/semantic/image_singularity.py
This metric gives each image a score that shows each image's uniqueness.
- A score of zero means that the image has duplicates in the dataset; on the other hand, a score close to one represents that image is quite unique. Among the duplicate images, we only give a non-zero score to a single image, and the rest will have a score of zero (for example, if there are five identical images, only four will have a score of zero). This way, these duplicate samples can be easily tagged and removed from the project.    
- Images that are near duplicates of each other will be shown side by side. 
- **To delete duplicate images:** You can set the quality filter to cover only zero values (that ends up with all the duplicate images), then use bulk tagging (e.g., with a tag like `Duplicate`) to tag all …
=> Feat (metric): image singularity

src/encord_active/app/model_quality/sub_pages/metrics.py, src/encord_active/lib/charts/precision_recall.py
There were no zooming property in altair chart and in the presence of many classes, texts were overlapping onto each other.
There are several things I am not sure on this PR:
- ontology path is sent to `create_pr_chart_plotly` function to get the original colors (and assign same colors to both subplots). Is sending the path correct way to do that?
- In order to synchronize two subplots (AP-AR for classes and Precision-Recall curve), I had to use for loop to iterate over different classes. Which does not seem to me ideal but I could not find another way to do that in plotly.
=> Feat (mAP plots): change to plotly graphs for interactivity

docs/docs/metrics/write-your-own.md, src/encord_active/app/data_quality/sub_pages/explorer.py, src/encord_active/lib/metrics/example.py, src/encord_active/lib/metrics/geometric/annotation_duplicates.py, src/encord_active/lib/metrics/geometric/hu_static.py, src/encord_active/lib/metrics/geometric/hu_temporal.py, src/encord_active/lib/metrics/geometric/image_border_closeness.py, src/encord_active/lib/metrics/geometric/object_size.py, src/encord_active/lib/metrics/geometric/occlusion_detection_video.py, src/encord_active/lib/metrics/heuristic/high_iou_changing_classes.py, src/encord_active/lib/metrics/heuristic/img_features.py, src/encord_active/lib/metrics/heuristic/missing_objects_and_wrong_tracks.py, src/encord_active/lib/metrics/heuristic/object_counting.py, src/encord_active/lib/metrics/heuristic/random.py, src/encord_active/lib/metrics/metric.py, src/encord_active/lib/metrics/semantic/image_singularity.py, src/encord_active/lib/metrics/semantic/img_classification_quality.py, src/encord_active/lib/metrics/semantic/img_object_quality.py, src/encord_active/lib/metrics/utils.py
As discussed in the last week's [meeting](https://www.notion.so/Design-planning-3-3-2023-07b3ada603724eeaaa4049df920f6014), explorer view is simplified by removing unnecessary text. A new attribute called `doc_url` is added to metrics that points to their documentation page. By clicking on the metric name, users can directly go to the related documentation page if it is provided (it goes to the main documentation page if this attribute does not exist in meta file, to not create a breaking change for the existing projects, sandbox etc.).
=> Feat (explorer view): Simplify UI

src/encord_active/lib/metrics/metadata.py
The inti function was broken due to the new metric meta data structure introduced in #199
=> fix: create metrics directory if not exists

CONTRIBUTING.md, README.md, examples/README.md, examples/building-a-custom-metric-function.ipynb, examples/download-sandbox-dataset.ipynb, examples/getting-started-with-coco-project.ipynb, examples/getting-started-with-encord-projects.ipynb, examples/maskrcnn-example/workflows/improve_dataset_by_fixing_labels.md, pyproject.toml, src/encord_active/lib/coco/__init__.py, src/encord_active/lib/constants.py, src/encord_active/lib/metrics/geometric/annotation_duplicates.py, src/encord_active/lib/metrics/geometric/hu_static.py, src/encord_active/lib/metrics/geometric/hu_temporal.py, src/encord_active/lib/metrics/geometric/image_border_closeness.py, src/encord_active/lib/metrics/geometric/object_size.py, src/encord_active/lib/metrics/geometric/occlusion_detection_video.py, src/encord_active/lib/metrics/heuristic/high_iou_changing_classes.py, src/encord_active/lib/metrics/heuristic/img_features.py, src/encord_active/lib/metrics/heuristic/missing_objects_and_wrong_tracks.py, src/encord_active/lib/metrics/heuristic/object_counting.py, src/encord_active/lib/metrics/heuristic/random.py, src/encord_active/lib/metrics/semantic/image_singularity.py, src/encord_active/lib/metrics/semantic/img_classification_quality.py, src/encord_active/lib/metrics/semantic/img_object_quality.py
Redirected all `https://encord-active-docs.web.app/` links in the codebase to the official Encord docs `https://docs.encord.com/active/docs`.
=> docs: redirect links to the official encord docs

src/encord_active/lib/labels/label_transformer.py
`Path.resolve()` tackles paths that contains parent references (`..`), while `Path.absolute()` doesn't.
=> fix: unexpected behaviour with relative path in init

pyproject.toml
As discussed [here](https://github.com/numba/numba/issues/8615) latest numpy and numba versions are incompatible in windows OS.
=> fix: numpy version

src/encord_active/app/actions_page/export_filter.py, src/encord_active/app/common/components/metric_summary.py, src/encord_active/app/common/components/prediction_grid.py, src/encord_active/app/common/components/similarities.py, src/encord_active/app/data_quality/sub_pages/explorer.py, src/encord_active/app/model_quality/sub_pages/false_positives.py, src/encord_active/app/model_quality/sub_pages/true_positives.py, src/encord_active/lib/common/image_utils.py, src/encord_active/lib/dataset/summary_utils.py, src/encord_active/lib/db/tags.py, src/encord_active/lib/encord/project_sync.py, src/encord_active/lib/project/__init__.py, src/encord_active/lib/project/project_file_structure.py, src/encord_active/lib/versioning/git.py
Now when exporting projects and creating subsets we create file mappings so as to avoid issues with versioning. 
This also fixes a versioning bug that discards you are changes when you're already on latest
=> fix(export): Use mappings instead of renaming files

docs/docs/active-learning/index.mdx, docs/docs/workflows/identify-outliers-edge-cases.md
Fixed:
Two broken links in the active learning section and one in the workflows section.
=> docs: fix broken links

.github/actions/setup-root-poetry-environment/action.yml
Update GH actions' poetry version and add prisma client generation so pylint/mypy recognise prisma autogenerated schemas/classes.
=> chore: set up prisma in GH actions

src/encord_active/app/common/state_hooks.py
if the state value is `False` it was returning the initial value
=> Fix : Default UseState

.github/workflows/pre-commit.yml
Making sure that our pipeline is using latest actions which use new GitHub env vars as old will soon the removed.
=> updating checkout action version - it use new github env vars

src/encord_active/app/actions_page/export_filter.py, src/encord_active/lib/common/utils.py, src/encord_active/lib/encord/actions.py, src/encord_active/lib/encord/local_sdk.py, src/encord_active/lib/file_structure/base.py, src/encord_active/lib/project/project_file_structure.py
Changes include:
1. Addition of `DataHashMapping` class to ease the overall process of storing mappings while allowing easy comprehension on what's being done (avoid passing dicts every time).
2. Change db's data hashes for the new ones that result from the `Export to Encord` feature.
3. Enable the `Export to Encord` feature.
=> feat: enable exported projects to work properly with prisma db

src/encord_active/lib/project/project.py
Small change to move db check and creation to project initialisation, so we can avoid race conditions related to creating the db when trying to add data in the async calls.
=> fix: db creation time in project import

src/encord_active/lib/metrics/semantic/image_difficulty.py
Skip this metric if there are a very few samples (less than # of classes)
=> fix (metrics): Image difficulty metric for few samples

src/encord_active/app/actions_page/export_filter.py, src/encord_active/cli/print.py, src/encord_active/lib/encord/utils.py
Now workflow projects have an integration which allows to send labels back to the annotation stage.
It recognises when a project is not a workflow project and provides information to the user about the next steps to make feature work.
It works nicely but still needs a progress bar, a confirmation pop up as it's very easy to send everything back to the labelling step if no filter has been selected which could cause a major issue and also register these operations in logs so in case the user mess up and wants to revert the mistake, (s)he can do so without having a backup copy of the project.
=> feat: add send labels to annotation stage

src/encord_active/app/actions_page/export_filter.py
Ensure that `No class` option always appear when filtering by object class.
=> misc(filter): ensure 'no_class' option always appear

src/encord_active/lib/db/helpers/tags.py, src/encord_active/server/routers/project.py
The labels in the label explorer were missing the data tags from the respective frames. Now, it's possible to visualise the tags applied over the frame where the label is and any modification to the data tags in the label explorer is reflected application wide.
=> fix: data tags interaction with labels in the label explorer

src/encord_active/lib/coco/parsers.py
Prediction import fails if the predictions have nested segmentations:
```json
[
{
"id": 1,
"image_id": 1,
"category_id": 1,
"score": 0.9,
"segmentation": [
[
577, 337, 577, 336, 578, 335, 578, 334
],
...
],
"bbox": [587.0, 343.0, 40.0, 32.0],
"area": 18.0,
"iscrowd": 0
}
]
```
This PR should fix that.
=> fix: coco prediction segmentations with nested lists

src/encord_active/app/model_quality/prediction_types/classification_type_builder.py
Non-premium views of the page display an connection error. This will only execute the querier when the feature is not disabled.
=> fix: exception when premium search disabled

src/encord_active/app/actions_page/export_filter.py, src/encord_active/lib/encord/actions.py
Basically, after creating some files in the newly created folder, if an error happens, `os.removedirs()` cannot delete them.
=> Fix (project creation): remove project folder properly

src/encord_active/lib/metrics/metadata.py
Handle the case where the original location of the built-in metrics doesn't longer exist, so we use the location of the active EA package.
=> fix: update built-in metrics' locations

src/encord_active/lib/common/data_utils.py
Minimise the number of open file descriptors for the temp cache implementation. As this seems to be the root cause behind the connectivity issues.
=> fix: limit opened file descriptors

src/encord_active/lib/metrics/geometric/image_border_closeness.py, src/encord_active/lib/project/project.py
Perf improvement to evaluation of 1 metric.
Main: performance improvement by assuring that when loading data the same url is used as metric iterations, this ensures that it runs through the same cache logic and hence avoids downloading all images twice.
=> fix: perf improvements, don't download images twice.

src/encord_active/lib/coco/encoder.py
Fixes two things:
1. The filters applied in the toolbox will now be obeyed - on the label row level
2. Export is much faster because we no longer download data to a directory the we delete right after. One consequence is that if the project is synced with Annotate, the `file_name` property of the images won't be a url to a location on disc but just the file name. Users will have to do the mapping them self. 
For completeness, local projects (not synced with Annotate) will get image entries looking like this:
while remote projects synced with Annotate will get
=> fix: obey filters from the toolbox when exporting to coco

docs/docs/active-learning/acquisition-functions.md
Bad indentation caused a help text to overflow and the whole text below was misinterpreted as help text also by MD.
=> docs: fix bad help text indentation

src/encord_active/lib/metrics/utils.py
The true names are already in the meta files, no need to parse file names anymore (which is also not always compatible with true names).
=> fix (metrics): get metric names from meta files

src/encord_active/app/auth/jwt.py, src/encord_active/server/dependencies.py
assert is not compiled to any code when optimizations are enabled: https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement
=> fix: do not use assert to verify deployment token

docs/docs/tutorials/touring-the-coco-dataset.mdx, docs/docs/user-guide/relabeling.mdx
When local images are displayed within html tags and the repo is migrated to the main docs, then the resulting paths are invalid.
=> fix: invalid image paths, use urls instead

examples/getting-started-with-coco-project.ipynb
Use generic names to not confuse users.
=> fix (examples): make generic names to avoid confusion

src/encord_active/cli/utils/coco.py, src/encord_active/lib/coco/importer.py
This PR fixes two issues:
- When a class in category is not exist in annotations, the default type was polygon, which leads to an error if the actual type is bbox in predictions.
- If the prediction shape type is different from the original COCO category type, we raise an error and show a message that reports the problem.
=> fix (COCO import): Assign two default object types for unknown types

src/encord_active/lib/common/data_utils.py, src/encord_active/lib/project/project.py
Added some actions at the `import data` step to avoid downloading/opening images unless it's necessary.
Passed the burden of downloading the images on online projects to the metrics management, when they actually require such download.
Also, made a quick fix to accept `videos` with whitespacing in their naming.
=> chore(import data): optimize by utilizing available image metadata when feasible

frontend_components/encord_active_components/frontend/src/components/explorer/Explorer.tsx
When filtering data on a "data metric" and then selecting a "label metric", explorer would be empty.
Now, when scope changes, filters will be cleared. 
One side-effect is that the pagination will be set to page one - which also didn't happen on reset previously.
=> fix: reset filters on scope change

src/encord_active/lib/model_predictions/writer.py
When importing predictions for image groups (or videos)
=> fix: use correct frame when importing predictions

src/encord_active/server/routers/queries/metric_query.py
This was working due to sqlite selecting the index by default, but adding the explicit order by is needed for proper correctness. (Backport from feat/no-disk).
=> fix: bug - add explicit order by

README.md
Update README: fix broken links, note Linux non-support, and added notebooks + resources section
- Replaced broken links (Colab notebook links were outdated) with the direct link to the GitHub-hosted sandbox dataset Colab notebook in the repository encord-team/encord-notebooks. I am open to changing this if you think
- Added a section to inform users that the library currently does not support Linux.
- Added section for encord notebooks repo
=> Update README: Linux non-support & Colab notebook

src/encord_active/public/active_project.py
An example of how to use the Active dataset.
Note that you can choose to include data URIs.
```python 
from pathlib import Path
from encord_active.public.active_project import ActiveProject
db_path = Path("fruits_only/encord-active.sqlite")
project = ActiveProject.from_db_file(db_path, project_name="Fruits [Workflow]")
print(project.ontology)
image_metrics = project.get_images_metrics(include_data_uris=True, include_data_tags=True)
print(image_metrics.describe())
preds = project.get_prediction_metrics(include_data_uris=True, include_data_tags=True)
print(preds.describe())
```
=> feat: active project export data
